
name: 'TestRob234523423'
description: 'Test rob'
branding:
  icon: 'info'
  color: 'green'
inputs:
  from-email:
    required: false

runs:
  using: 'docker'
  image: 'docker://acheronbv/acheron-database-manager:latest-1.3.50'
  #pre-entrypoint: '/etc/aliases.sh'
  entrypoint: python /usr/local/lib/python3.9/site-packages/opt/acheron/lint.py -h
  #Spost-entrypoint: 'cleanup.sh'
